### PR TITLE
Fix "see also" links on suspense page

### PR DESCRIPTION
**Pull request by bruceharris**

### CODE REVIEW

**Comment by voliva** [comment]
Hey @bruceharris, thank you for raising this.

However the links on https://react-rxjs.org/docs/api/core/suspense all seem to work on my end, is this the page the links are broken?

The CI flagged that the new links of this PR are broken.

```
Error: Broken links found!

- Page path = /docs/api/core/suspense:
   -> link to ../../utils/suspend (resolved as: /docs/utils/suspend)
   -> link to ../../utils/suspended (resolved as: /docs/utils/suspended)
```

**Comment by bruceharris** [comment]
Hmm, links go to "page not found" for me. broken links

**Comment by voliva** [comment]
Ok I see, it happens when accessing directly into the page. If you navigate through the menu to SUSPENSE, then the links work alright.

The only difference I see is that when navigating through the menu the URL doesn't end with /, whereas when navigating directly it does end with /. I'm thinking Docusaurs bug? I'll try to investigate later on.

**Comment by voliva** [comment]
Indeed, it was an issue on docusaurus + github pages: https://github.com/facebook/docusaurus/issues/5026

They released a newer version with a config option to fix it, so I raised #56 that does the upgrade and configures it.

**Comment by bruceharris** [comment]
👍 thanks @voliva !

**Pull request closed without merging**
